[Eth]
NetworkId = 61022
SyncMode = "full"
TrieCleanCacheRejournal= 300000000000
TrieTimeout = 20000000000
RPCTxFeeCap = 6.0


[Eth.Miner]
GasCeil =  63000000
GasPrice = 2000000
Recommit = 3000000000

[Eth.TxPool]
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 600000000000
PriceLimit = 2000000
PriceBump = 10
AccountSlots = 64
GlobalSlots = 10240
AccountQueue = 32
GlobalQueue = 10240
Lifetime = 1800000000000

[Node]
DataDir = "./data"
InsecureUnlockAllowed = true
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ['eth', 'net', 'web3', 'engine', 'debug', 'txpool']

WSHost = "0.0.0.0"
WSPort = 8546
WSModules = ['eth', 'net', 'web3', 'engine', 'debug', 'txpool']

GraphQLVirtualHosts = ["localhost"]


[Node.P2P]
MaxPeers = 50
NoDiscovery = true
StaticNodes = [] 
ListenAddr = ":33687"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
